[package]
name = "rabbitmq_http_client"
version = "0.16.0"
edition = "2021"

description = "RabbitMQ HTTP API client"
license = "MIT OR Apache-2.0"

[lib]
# doctests for async client must be wrapped
# with a Tokio block_on block or marked with no_run,
# or skipped entirely, which is what we want
doctest = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde-aux = "4.5"
serde_json = "1"
rand = "0.8"
ring = "0.17"
rbase64 = "2"
percent-encoding = { version = "2", optional = true }
tabled = { version = "0.17", features = ["derive", "macros"], optional = true }

reqwest = { version = "0.12.12", features = [
    "json",
    "multipart",
], optional = true }
backtrace = { version = "0.3", optional = true }
thiserror = { version = "2", optional = true }


[dev-dependencies]
amqprs = {  version = "2"}
cargo-nextest = "0.9.87"
regex = { version = "1", features = ["std"] }

[features]
default = ["core", "blocking"]
core = []
async = [
    "dep:reqwest",
    "dep:thiserror",
    "dep:backtrace",
    "dep:percent-encoding"
]
blocking = [
    "dep:reqwest",
    "reqwest/blocking",
    "dep:thiserror",
    "dep:backtrace",
    "dep:percent-encoding",
]
tabled = ["dep:tabled"]
