[package]
name = "rabbitmq_http_client"
version = "0.7.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json", "multipart", "blocking", "rustls-tls"] }
thiserror = "1"
serde = { version = "1.0", features = ["derive", "std"] }
serde-aux = "4.5"
serde_json = "1"
percent-encoding = "2"
rand = "0.8"
ring = "0.17"
rbase64 = "2"
tabled = { version = "0.16", features = ["derive", "macros"], optional = true }

[dev-dependencies]
amqprs = "1"
# tokio = { version = "1", features = ["rt", "net"] }

[features]
default = ["core"]
core = []
tabled = ["dep:tabled"]
