[package]
name = "rabbitmq_http_client"
version = "0.9.0"
edition = "2021"

description = "RabbitMQ HTTP API client"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde-aux = "4.5"
serde_json = "1"
rand = "0.8"
ring = "0.17"
rbase64 = "2"
reqwest = { version = "0.12", features = [
    "json",
    "multipart",
], optional = true }
thiserror = { version = "2", optional = true }
percent-encoding = { version = "2", optional = true }
tabled = { version = "0.16", features = ["derive", "macros"], optional = true }

[dev-dependencies]
amqprs = {  version = "2"}
cargo-nextest = "0.9.84"

[features]
default = ["core", "blocking"]
core = []
async = ["dep:reqwest", "dep:thiserror", "dep:percent-encoding"]
blocking = [
    "dep:reqwest",
    "reqwest/blocking",
    "dep:thiserror",
    "dep:percent-encoding",
]
tabled = ["dep:tabled"]
