name: CI

on: [push, pull_request]

env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always
  TEST_STATS_DELAY: 5000

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Lint (clippy)
        run: cargo clippy --all-features

      - name: Lint (rustfmt)
        run: cargo fmt --all --check

  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: [ stable ]

    services:
      rabbitmq:
        image: rabbitmq:4-management
        ports:
          - 15672:15672
          - 5672:5672

    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust-version }}

      - name: Install cargo-nextest
        run: cargo install cargo-nextest

      - name: Wait for node to start booting
        run: sleep 15

      - name: Configure broker
        run: RUST_HTTP_API_CLIENT_RABBITMQCTL=DOCKER:${{job.services.rabbitmq.id}} bin/ci/before_build.sh

      - name: Run tests
        run: RUST_BACKTRACE=1 TEST_STATS_DELAY=2000 NEXTEST_RETRIES=4 cargo nextest run --workspace --no-fail-fast --all-features
